import numpy as np
import pandas as pd
from pandas_datareader import data as web
import datetime
import sys

start = datetime.date(1975,1,1)
end = datetime.date.today()

A = web.DataReader('A', 'yahoo',start,end)
AAL = web.DataReader('AAL', 'yahoo',start,end)
AAP = web.DataReader('AAP', 'yahoo',start,end)
AAPL = web.DataReader('AAPL', 'yahoo',start,end)

ABBV = web.DataReader('ABBV', 'yahoo',start,end)
ABC = web.DataReader('ABC', 'yahoo',start,end)
ABT = web.DataReader('ABT', 'yahoo',start,end)
ACN = web.DataReader('ACN', 'yahoo',start,end)
ADBE = web.DataReader('ADBE', 'yahoo',start,end)
ADI = web.DataReader('ADI', 'yahoo',start,end)
ADM = web.DataReader('ADM', 'yahoo',start,end)
ADP = web.DataReader('ADP', 'yahoo',start,end)
ADS = web.DataReader('ADS', 'yahoo',start,end)
ADSK = web.DataReader('ADSK', 'yahoo',start,end)
AEE = web.DataReader('AEE', 'yahoo',start,end)
AEP = web.DataReader('AEP', 'yahoo',start,end)
AES = web.DataReader('AES', 'yahoo',start,end)
AET = web.DataReader('AET', 'yahoo',start,end)
AFL = web.DataReader('AFL', 'yahoo',start,end)
AGN = web.DataReader('AGN', 'yahoo',start,end)
AIG = web.DataReader('AIG', 'yahoo',start,end)
AIV = web.DataReader('AIV', 'yahoo',start,end)
AIZ = web.DataReader('AIZ', 'yahoo',start,end)
AJG = web.DataReader('AJG', 'yahoo',start,end)
AKAM = web.DataReader('AKAM', 'yahoo',start,end)
ALB = web.DataReader('ALB', 'yahoo',start,end)
ALK = web.DataReader('ALK', 'yahoo',start,end)
ALL = web.DataReader('ALL', 'yahoo',start,end)
ALLE = web.DataReader('ALLE', 'yahoo',start,end)
ALXN = web.DataReader('ALXN', 'yahoo',start,end)
AMAT = web.DataReader('AMAT', 'yahoo',start,end)
AME = web.DataReader('AME', 'yahoo',start,end)
AMG = web.DataReader('AMG', 'yahoo',start,end)
AMGN = web.DataReader('AMGN', 'yahoo',start,end)
AMP = web.DataReader('AMP', 'yahoo',start,end)
AMT = web.DataReader('AMT', 'yahoo',start,end)
AMZN = web.DataReader('AMZN', 'yahoo',start,end)
AN = web.DataReader('AN', 'yahoo',start,end)
ANTM = web.DataReader('ANTM', 'yahoo',start,end)
AON = web.DataReader('AON', 'yahoo',start,end)
APA = web.DataReader('APA', 'yahoo',start,end)
APC = web.DataReader('APC', 'yahoo',start,end)
APD = web.DataReader('APD', 'yahoo',start,end)
APH = web.DataReader('APH', 'yahoo',start,end)
ATVI = web.DataReader('ATVI', 'yahoo',start,end)
AVB = web.DataReader('AVB', 'yahoo',start,end)
AVGO = web.DataReader('AVGO', 'yahoo',start,end)
AVY = web.DataReader('AVY', 'yahoo',start,end)
AWK = web.DataReader('AWK', 'yahoo',start,end)
AXP = web.DataReader('AXP', 'yahoo',start,end)
AYI = web.DataReader('AYI', 'yahoo',start,end)
AZO = web.DataReader('AZO', 'yahoo',start,end)

BA = web.DataReader('BA', 'yahoo',start,end)
BAC = web.DataReader('BAC', 'yahoo',start,end)
BAX = web.DataReader('BAX', 'yahoo',start,end)
BBBY = web.DataReader('BBBY', 'yahoo',start,end)
BBT = web.DataReader('BBT', 'yahoo',start,end)
BBY = web.DataReader('BBY', 'yahoo',start,end)
BCR = web.DataReader('BCR', 'yahoo',start,end)
BDX = web.DataReader('BDX', 'yahoo',start,end)
BEN = web.DataReader('BEN', 'yahoo',start,end)
BFB = web.DataReader('BF-B', 'yahoo',start,end)
BHI = web.DataReader('BHI', 'yahoo',start,end)
BIIB = web.DataReader('BIIB', 'yahoo',start,end)
BK = web.DataReader('BK', 'yahoo',start,end)
BLK = web.DataReader('BLK', 'yahoo',start,end)
BLL = web.DataReader('BLL', 'yahoo',start,end)
BMY = web.DataReader('BMY', 'yahoo',start,end)
BRKB = web.DataReader('BRK-B', 'yahoo',start,end)
BSX = web.DataReader('BSX', 'yahoo',start,end)
BWA = web.DataReader('BWA', 'yahoo',start,end)
BXP = web.DataReader('BXP', 'yahoo',start,end)

C = web.DataReader('C', 'yahoo',start,end)
CA = web.DataReader('CA', 'yahoo',start,end)
CAG = web.DataReader('CAG', 'yahoo',start,end)
CAH = web.DataReader('CAH', 'yahoo',start,end)
CAT = web.DataReader('CAT', 'yahoo',start,end)
CB = web.DataReader('CB', 'yahoo',start,end)
CBG = web.DataReader('CBG', 'yahoo',start,end)
CBS = web.DataReader('CBS', 'yahoo',start,end)
CCI = web.DataReader('CCI', 'yahoo',start,end)
CCL = web.DataReader('CCL', 'yahoo',start,end)
CELG = web.DataReader('CELG', 'yahoo',start,end)
CERN = web.DataReader('CERN', 'yahoo',start,end)
CF = web.DataReader('CF', 'yahoo',start,end)
CFG = web.DataReader('CFG', 'yahoo',start,end)
CHD = web.DataReader('CHD', 'yahoo',start,end)
CHK = web.DataReader('CHK', 'yahoo',start,end)
CHRW = web.DataReader('CHRW', 'yahoo',start,end)
CHTR = web.DataReader('CHTR', 'yahoo',start,end)
CI = web.DataReader('CI', 'yahoo',start,end)
CINF = web.DataReader('CINF', 'yahoo',start,end)
CL = web.DataReader('CL', 'yahoo',start,end)
CLX = web.DataReader('CLX', 'yahoo',start,end)
CMA = web.DataReader('CMA', 'yahoo',start,end)
CMCSA = web.DataReader('CMCSA', 'yahoo',start,end)
CME = web.DataReader('CME', 'yahoo',start,end)
CMG = web.DataReader('CMG', 'yahoo',start,end)
CMI = web.DataReader('CMI', 'yahoo',start,end)
CMS = web.DataReader('CMS', 'yahoo',start,end)
CNC = web.DataReader('CNC', 'yahoo',start,end)
CNP = web.DataReader('CNP', 'yahoo',start,end)
COF = web.DataReader('COF', 'yahoo',start,end)
COG = web.DataReader('COG', 'yahoo',start,end)
COH = web.DataReader('COH', 'yahoo',start,end)
COL = web.DataReader('COL', 'yahoo',start,end)
COO = web.DataReader('COO', 'yahoo',start,end)
COP = web.DataReader('COP', 'yahoo',start,end)
COST = web.DataReader('COST', 'yahoo',start,end)
COTY = web.DataReader('COTY', 'yahoo',start,end)
CPB = web.DataReader('CPB', 'yahoo',start,end)
CRM = web.DataReader('CRM', 'yahoo',start,end)
CSCO = web.DataReader('CSCO', 'yahoo',start,end)
CSRA = web.DataReader('CSRA', 'yahoo',start,end)
CSX = web.DataReader('CSX', 'yahoo',start,end)
CTAS = web.DataReader('CTAS', 'yahoo',start,end)
CTL = web.DataReader('CTL', 'yahoo',start,end)
CTSH = web.DataReader('CTSH', 'yahoo',start,end)
CTXS = web.DataReader('CTXS', 'yahoo',start,end)
CVS = web.DataReader('CVS', 'yahoo',start,end)
CVX = web.DataReader('CVX', 'yahoo',start,end)

CXO = web.DataReader('CXO', 'yahoo',start,end)

D = web.DataReader('D', 'yahoo',start,end)
DAL = web.DataReader('DAL', 'yahoo',start,end)
DD = web.DataReader('DD', 'yahoo',start,end)
DE = web.DataReader('DE', 'yahoo',start,end)
DFS = web.DataReader('DFS', 'yahoo',start,end)
DG = web.DataReader('DG', 'yahoo',start,end)
DGX = web.DataReader('DGX', 'yahoo',start,end)
DHI = web.DataReader('DHI', 'yahoo',start,end)
DHR = web.DataReader('DHR', 'yahoo',start,end)
DIS = web.DataReader('DIS', 'yahoo',start,end)
DISCA = web.DataReader('DISCA', 'yahoo',start,end)
DISCK = web.DataReader('DISCK', 'yahoo',start,end)
DLPH = web.DataReader('DLPH', 'yahoo',start,end)
DLR = web.DataReader('DLR', 'yahoo',start,end)
DLTR = web.DataReader('DLTR', 'yahoo',start,end)
DNB = web.DataReader('DNB', 'yahoo',start,end)
DOV = web.DataReader('DOV', 'yahoo',start,end)
DOW = web.DataReader('DOW', 'yahoo',start,end)
DPS = web.DataReader('DPS', 'yahoo',start,end)
DRI = web.DataReader('DRI', 'yahoo',start,end)
DTE = web.DataReader('DTE', 'yahoo',start,end)
DUK = web.DataReader('DUK', 'yahoo',start,end)
DVA = web.DataReader('DVA', 'yahoo',start,end)
DVN = web.DataReader('DVN', 'yahoo',start,end)
print '1'
EA = web.DataReader('EA', 'yahoo',start,end)
EBAY = web.DataReader('EBAY', 'yahoo',start,end)
ECL = web.DataReader('ECL', 'yahoo',start,end)
ED = web.DataReader('ED', 'yahoo',start,end)
EFX = web.DataReader('EFX', 'yahoo',start,end)
EIX = web.DataReader('EIX', 'yahoo',start,end)
EL = web.DataReader('EL', 'yahoo',start,end)
EMN = web.DataReader('EMN', 'yahoo',start,end)
EMR = web.DataReader('EMR', 'yahoo',start,end)
ENDP = web.DataReader('ENDP', 'yahoo',start,end)
EOG = web.DataReader('EOG', 'yahoo',start,end)
EQIX = web.DataReader('EQIX', 'yahoo',start,end)
EQR = web.DataReader('EQR', 'yahoo',start,end)
EQT = web.DataReader('EQT', 'yahoo',start,end)
ES = web.DataReader('ES', 'yahoo',start,end)
ESRX = web.DataReader('ESRX', 'yahoo',start,end)
ESS = web.DataReader('ESS', 'yahoo',start,end)
ETFC = web.DataReader('ETFC', 'yahoo',start,end)
ETN = web.DataReader('ETN', 'yahoo',start,end)
ETR = web.DataReader('ETR', 'yahoo',start,end)
EW = web.DataReader('EW', 'yahoo',start,end)
EXC = web.DataReader('EXC', 'yahoo',start,end)
EXPD = web.DataReader('EXPD', 'yahoo',start,end)
EXPE = web.DataReader('EXPE', 'yahoo',start,end)
EXR = web.DataReader('EXR', 'yahoo',start,end)

F = web.DataReader('F', 'yahoo',start,end)
FAST = web.DataReader('FAST', 'yahoo',start,end)
FB = web.DataReader('FB', 'yahoo',start,end)
FBHS = web.DataReader('FBHS', 'yahoo',start,end)
FCX = web.DataReader('FCX', 'yahoo',start,end)
FDX = web.DataReader('FDX', 'yahoo',start,end)
FE = web.DataReader('FE', 'yahoo',start,end)
FFIV = web.DataReader('FFIV', 'yahoo',start,end)
FIS = web.DataReader('FIS', 'yahoo',start,end)
FISV = web.DataReader('FISV', 'yahoo',start,end)
FITB = web.DataReader('FITB', 'yahoo',start,end)
FL = web.DataReader('FL', 'yahoo',start,end)
FLIR = web.DataReader('FLIR', 'yahoo',start,end)
FLR = web.DataReader('FLR', 'yahoo',start,end)
FLS = web.DataReader('FLS', 'yahoo',start,end)
FMC = web.DataReader('FMC', 'yahoo',start,end)
FOX = web.DataReader('FOX', 'yahoo',start,end)
FOXA = web.DataReader('FOXA', 'yahoo',start,end)
FRT = web.DataReader('FRT', 'yahoo',start,end)
FSLR = web.DataReader('FSLR', 'yahoo',start,end)
FTI = web.DataReader('FTI', 'yahoo',start,end)
FTR = web.DataReader('FTR', 'yahoo',start,end)
FTV = web.DataReader('FTV', 'yahoo',start,end)

GD = web.DataReader('GD', 'yahoo',start,end)
GE = web.DataReader('GE', 'yahoo',start,end)
GGP = web.DataReader('GGP', 'yahoo',start,end)
GILD = web.DataReader('GILD', 'yahoo',start,end)
GIS = web.DataReader('GIS', 'yahoo',start,end)
GLW = web.DataReader('GLW', 'yahoo',start,end)
GM = web.DataReader('GM', 'yahoo',start,end)
GOOG = web.DataReader('GOOG', 'yahoo',start,end)
GOOGL = web.DataReader('GOOGL', 'yahoo',start,end)
GPC = web.DataReader('GPC', 'yahoo',start,end)
GPN = web.DataReader('GPN', 'yahoo',start,end)
GPS = web.DataReader('GPS', 'yahoo',start,end)
GRMN = web.DataReader('GRMN', 'yahoo',start,end)
GS = web.DataReader('GS', 'yahoo',start,end)
GT = web.DataReader('GT', 'yahoo',start,end)
GWW = web.DataReader('GWW', 'yahoo',start,end)

HAL = web.DataReader('HAL', 'yahoo',start,end)
HAR = web.DataReader('HAR', 'yahoo',start,end)
HAS = web.DataReader('HAS', 'yahoo',start,end)
HBAN = web.DataReader('HBAN', 'yahoo',start,end)
HBI = web.DataReader('HBI', 'yahoo',start,end)
HCA = web.DataReader('HCA', 'yahoo',start,end)
HCN = web.DataReader('HCN', 'yahoo',start,end)
HCP = web.DataReader('HCP', 'yahoo',start,end)
HD = web.DataReader('HD', 'yahoo',start,end)
HES = web.DataReader('HES', 'yahoo',start,end)
HIG = web.DataReader('HIG', 'yahoo',start,end)
HOG = web.DataReader('HOG', 'yahoo',start,end)
HOLX = web.DataReader('HOLX', 'yahoo',start,end)
HON = web.DataReader('HON', 'yahoo',start,end)
HP = web.DataReader('HP', 'yahoo',start,end)
HPE = web.DataReader('HPE', 'yahoo',start,end)
HPQ = web.DataReader('HPQ', 'yahoo',start,end)
HRB = web.DataReader('HRB', 'yahoo',start,end)
HRL = web.DataReader('HRL', 'yahoo',start,end)
HRS = web.DataReader('HRS', 'yahoo',start,end)
HSIC = web.DataReader('HSIC', 'yahoo',start,end)
HST = web.DataReader('HST', 'yahoo',start,end)
HSY = web.DataReader('HSY', 'yahoo',start,end)
HUM = web.DataReader('HUM', 'yahoo',start,end)

IBM = web.DataReader('IBM', 'yahoo',start,end)
ICE = web.DataReader('ICE', 'yahoo',start,end)
IFF = web.DataReader('IFF', 'yahoo',start,end)
ILMN = web.DataReader('ILMN', 'yahoo',start,end)
INTC = web.DataReader('INTC', 'yahoo',start,end)
INTU = web.DataReader('INTU', 'yahoo',start,end)
IP = web.DataReader('IP', 'yahoo',start,end)
IPG = web.DataReader('IPG', 'yahoo',start,end)
IR = web.DataReader('IR', 'yahoo',start,end)
IRM = web.DataReader('IRM', 'yahoo',start,end)
ISRG = web.DataReader('ISRG', 'yahoo',start,end)
ITW = web.DataReader('ITW', 'yahoo',start,end)
IVZ = web.DataReader('IVZ', 'yahoo',start,end)

JBHT = web.DataReader('JBHT', 'yahoo',start,end)
JCI = web.DataReader('JCI', 'yahoo',start,end)
JEC = web.DataReader('JEC', 'yahoo',start,end)
JNJ = web.DataReader('JNJ', 'yahoo',start,end)
JNPR = web.DataReader('JNPR', 'yahoo',start,end)
JPM = web.DataReader('JPM', 'yahoo',start,end)
JWN = web.DataReader('JWN', 'yahoo',start,end)

K = web.DataReader('K', 'yahoo',start,end)
KEY = web.DataReader('KEY', 'yahoo',start,end)
KHC = web.DataReader('KHC', 'yahoo',start,end)
KIM = web.DataReader('KIM', 'yahoo',start,end)
KLAC = web.DataReader('KLAC', 'yahoo',start,end)
KMB = web.DataReader('KMB', 'yahoo',start,end)
KMI = web.DataReader('KMI', 'yahoo',start,end)
KMX = web.DataReader('KMX', 'yahoo',start,end)
KO = web.DataReader('KO', 'yahoo',start,end)
KORS = web.DataReader('KORS', 'yahoo',start,end)
KR = web.DataReader('KR', 'yahoo',start,end)
KSS = web.DataReader('KSS', 'yahoo',start,end)
KSU = web.DataReader('KSU', 'yahoo',start,end)

L = web.DataReader('L', 'yahoo',start,end)
LB = web.DataReader('LB', 'yahoo',start,end)
LEG = web.DataReader('LEG', 'yahoo',start,end)
LEN = web.DataReader('LEN', 'yahoo',start,end)
LH = web.DataReader('LH', 'yahoo',start,end)
LKQ = web.DataReader('LKQ', 'yahoo',start,end)
LLL = web.DataReader('LLL', 'yahoo',start,end)
LLTC = web.DataReader('LLTC', 'yahoo',start,end)
LLY = web.DataReader('LLY', 'yahoo',start,end)
LM = web.DataReader('LM', 'yahoo',start,end)
LMT = web.DataReader('LMT', 'yahoo',start,end)
LNC = web.DataReader('LNC', 'yahoo',start,end)
LNT = web.DataReader('LNT', 'yahoo',start,end)
LOW = web.DataReader('LOW', 'yahoo',start,end)
LRCX = web.DataReader('LRCX', 'yahoo',start,end)
LUK = web.DataReader('LUK', 'yahoo',start,end)
LUV = web.DataReader('LUV', 'yahoo',start,end)
LVLT = web.DataReader('LVLT', 'yahoo',start,end)
LYB = web.DataReader('LYB', 'yahoo',start,end)
print '2'
M = web.DataReader('M', 'yahoo',start,end)
MA = web.DataReader('MA', 'yahoo',start,end)
MAC = web.DataReader('MAC', 'yahoo',start,end)
MAR = web.DataReader('MAR', 'yahoo',start,end)
MAS = web.DataReader('MAS', 'yahoo',start,end)
MAT = web.DataReader('MAT', 'yahoo',start,end)
MCD = web.DataReader('MCD', 'yahoo',start,end)
MCHP = web.DataReader('MCHP', 'yahoo',start,end)
MCK = web.DataReader('MCK', 'yahoo',start,end)
MCO = web.DataReader('MCO', 'yahoo',start,end)
MDLZ = web.DataReader('MDLZ', 'yahoo',start,end)
MDT = web.DataReader('MDT', 'yahoo',start,end)
MET = web.DataReader('MET', 'yahoo',start,end)
MHK = web.DataReader('MHK', 'yahoo',start,end)
MJN = web.DataReader('MJN', 'yahoo',start,end)
MKC = web.DataReader('MKC', 'yahoo',start,end)
MLM = web.DataReader('MLM', 'yahoo',start,end)
MMC = web.DataReader('MMC', 'yahoo',start,end)
MMM = web.DataReader('MMM', 'yahoo',start,end)
MNK = web.DataReader('MNK', 'yahoo',start,end)
MNST = web.DataReader('MNST', 'yahoo',start,end)
MO = web.DataReader('MO', 'yahoo',start,end)
MON = web.DataReader('MON', 'yahoo',start,end)
MOS = web.DataReader('MOS', 'yahoo',start,end)
MPC = web.DataReader('MPC', 'yahoo',start,end)
MRK = web.DataReader('MRK', 'yahoo',start,end)
MRO = web.DataReader('MRO', 'yahoo',start,end)
MS = web.DataReader('MS', 'yahoo',start,end)
MSFT = web.DataReader('MSFT', 'yahoo',start,end)
MSI = web.DataReader('MSI', 'yahoo',start,end)
MTB = web.DataReader('MTB', 'yahoo',start,end)
MTD = web.DataReader('MTD', 'yahoo',start,end)
MU = web.DataReader('MU', 'yahoo',start,end)
MUR = web.DataReader('MUR', 'yahoo',start,end)
MYL = web.DataReader('MYL', 'yahoo',start,end)

NAVI = web.DataReader('NAVI', 'yahoo',start,end)
NBL = web.DataReader('NBL', 'yahoo',start,end)
NDAQ = web.DataReader('NDAQ', 'yahoo',start,end)
NEE = web.DataReader('NEE', 'yahoo',start,end)
NEM = web.DataReader('NEM', 'yahoo',start,end)
NFLX = web.DataReader('NFLX', 'yahoo',start,end)
NFX = web.DataReader('NFX', 'yahoo',start,end)
NI = web.DataReader('NI', 'yahoo',start,end)
NKE = web.DataReader('NKE', 'yahoo',start,end)
NLSN = web.DataReader('NLSN', 'yahoo',start,end)
NOC = web.DataReader('NOC', 'yahoo',start,end)
NOV = web.DataReader('NOV', 'yahoo',start,end)
NRG = web.DataReader('NRG', 'yahoo',start,end)
NSC = web.DataReader('NSC', 'yahoo',start,end)
NTAP = web.DataReader('NTAP', 'yahoo',start,end)
NTRS = web.DataReader('NTRS', 'yahoo',start,end)
NUE = web.DataReader('NUE', 'yahoo',start,end)
NVDA = web.DataReader('NVDA', 'yahoo',start,end)
NWL = web.DataReader('NWL', 'yahoo',start,end)
NWS = web.DataReader('NWS', 'yahoo',start,end)
NWSA = web.DataReader('NWSA', 'yahoo',start,end)

O = web.DataReader('O', 'yahoo',start,end)
OI = web.DataReader('OI', 'yahoo',start,end)
OKE = web.DataReader('OKE', 'yahoo',start,end)
OMC = web.DataReader('OMC', 'yahoo',start,end)
ORCL = web.DataReader('ORCL', 'yahoo',start,end)
ORLY = web.DataReader('ORLY', 'yahoo',start,end)
OXY = web.DataReader('OXY', 'yahoo',start,end)

PAYX = web.DataReader('PAYX', 'yahoo',start,end)
PBCT = web.DataReader('PBCT', 'yahoo',start,end)
PBI = web.DataReader('PBI', 'yahoo',start,end)
PCAR = web.DataReader('PCAR', 'yahoo',start,end)
PCG = web.DataReader('PCG', 'yahoo',start,end)
PCLN = web.DataReader('PCLN', 'yahoo',start,end)
PDCO = web.DataReader('PDCO', 'yahoo',start,end)
PEG = web.DataReader('PEG', 'yahoo',start,end)
PFE = web.DataReader('PFE', 'yahoo',start,end)
PEP = web.DataReader('PEP', 'yahoo',start,end)
PFG = web.DataReader('PFG', 'yahoo',start,end)
PG = web.DataReader('PG', 'yahoo',start,end)
PGR = web.DataReader('PGR', 'yahoo',start,end)
PH = web.DataReader('PH', 'yahoo',start,end)
PHM = web.DataReader('PHM', 'yahoo',start,end)
PKI = web.DataReader('PKI', 'yahoo',start,end)
PLD = web.DataReader('PLD', 'yahoo',start,end)
PM = web.DataReader('PM', 'yahoo',start,end)
PNC = web.DataReader('PNC', 'yahoo',start,end)
PNR = web.DataReader('PNR', 'yahoo',start,end)
PNW = web.DataReader('PNW', 'yahoo',start,end)
PPG = web.DataReader('PPG', 'yahoo',start,end)
PPL = web.DataReader('PPL', 'yahoo',start,end)
PRGO = web.DataReader('PRGO', 'yahoo',start,end)
PRU = web.DataReader('PRU', 'yahoo',start,end)
PSA = web.DataReader('PSA', 'yahoo',start,end)
PSX = web.DataReader('PSX', 'yahoo',start,end)
PVH = web.DataReader('PVH', 'yahoo',start,end)
PWR = web.DataReader('PWR', 'yahoo',start,end)
PX = web.DataReader('PX', 'yahoo',start,end)
PXD = web.DataReader('PXD', 'yahoo',start,end)
PYPL = web.DataReader('PYPL', 'yahoo',start,end)

QCOM = web.DataReader('QCOM', 'yahoo',start,end)
QRVO = web.DataReader('QRVO', 'yahoo',start,end)

R = web.DataReader('R', 'yahoo',start,end)
RAI = web.DataReader('RAI', 'yahoo',start,end)
RCL = web.DataReader('RCL', 'yahoo',start,end)
REGN = web.DataReader('REGN', 'yahoo',start,end)
RF = web.DataReader('RF', 'yahoo',start,end)
RHI = web.DataReader('RHI', 'yahoo',start,end)
RHT = web.DataReader('RHT', 'yahoo',start,end)
RIG = web.DataReader('RIG', 'yahoo',start,end)
RL = web.DataReader('RL', 'yahoo',start,end)
ROK = web.DataReader('ROK', 'yahoo',start,end)
ROP = web.DataReader('ROP', 'yahoo',start,end)
ROST = web.DataReader('ROST', 'yahoo',start,end)
RRC = web.DataReader('RRC', 'yahoo',start,end)
RSG = web.DataReader('RSG', 'yahoo',start,end)
RTN = web.DataReader('RTN', 'yahoo',start,end)

SBUX = web.DataReader('SBUX', 'yahoo',start,end)
SCG = web.DataReader('SCG', 'yahoo',start,end)
SCHW = web.DataReader('SCHW', 'yahoo',start,end)
SE = web.DataReader('SE', 'yahoo',start,end)
SEE = web.DataReader('SEE', 'yahoo',start,end)
SHW = web.DataReader('SHW', 'yahoo',start,end)
SIG = web.DataReader('SIG', 'yahoo',start,end)
SJM = web.DataReader('SJM', 'yahoo',start,end)
SLB = web.DataReader('SLB', 'yahoo',start,end)
SLG = web.DataReader('SLG', 'yahoo',start,end)
SNA = web.DataReader('SNA', 'yahoo',start,end)
SNI = web.DataReader('SNI', 'yahoo',start,end)
SO = web.DataReader('SO', 'yahoo',start,end)
SPG = web.DataReader('SPG', 'yahoo',start,end)
SPGI = web.DataReader('SPGI', 'yahoo',start,end)
SPLS = web.DataReader('SPLS', 'yahoo',start,end)
SRCL = web.DataReader('SRCL', 'yahoo',start,end)
SRE = web.DataReader('SRE', 'yahoo',start,end)
STI = web.DataReader('STI', 'yahoo',start,end)
STJ = web.DataReader('STJ', 'yahoo',start,end)
STT = web.DataReader('STT', 'yahoo',start,end)
STX = web.DataReader('STX', 'yahoo',start,end)
STZ = web.DataReader('STZ', 'yahoo',start,end)
SWK = web.DataReader('SWK', 'yahoo',start,end)
SWKS = web.DataReader('SWKS', 'yahoo',start,end)
SWN = web.DataReader('SWN', 'yahoo',start,end)
SYF = web.DataReader('SYF', 'yahoo',start,end)
SYK = web.DataReader('SYK', 'yahoo',start,end)
SYMC = web.DataReader('SYMC', 'yahoo',start,end)
SYY = web.DataReader('SYY', 'yahoo',start,end)
print '3'
T = web.DataReader('T', 'yahoo',start,end)
TAP = web.DataReader('TAP', 'yahoo',start,end)
TDC = web.DataReader('TDC', 'yahoo',start,end)
TDG = web.DataReader('TDG', 'yahoo',start,end)
TEL = web.DataReader('TEL', 'yahoo',start,end)
TGNA = web.DataReader('TGNA', 'yahoo',start,end)
TGT = web.DataReader('TGT', 'yahoo',start,end)
TIF = web.DataReader('TIF', 'yahoo',start,end)
TJX = web.DataReader('TJX', 'yahoo',start,end)
TMK = web.DataReader('TMK', 'yahoo',start,end)
TMO = web.DataReader('TMO', 'yahoo',start,end)
TRIP = web.DataReader('TRIP', 'yahoo',start,end)
TROW = web.DataReader('TROW', 'yahoo',start,end)
TRV = web.DataReader('TRV', 'yahoo',start,end)
TSCO = web.DataReader('TSCO', 'yahoo',start,end)
TSN = web.DataReader('TSN', 'yahoo',start,end)
TSO = web.DataReader('TSO', 'yahoo',start,end)
TSS = web.DataReader('TSS', 'yahoo',start,end)
TWX = web.DataReader('TWX', 'yahoo',start,end)
TXN = web.DataReader('TXN', 'yahoo',start,end)
TXT = web.DataReader('TXT', 'yahoo',start,end)

UA = web.DataReader('UA', 'yahoo',start,end)
UAC = web.DataReader('UA.C', 'yahoo',start,end)
UAL = web.DataReader('UAL', 'yahoo',start,end)
UDR = web.DataReader('UDR', 'yahoo',start,end)
UHS = web.DataReader('UHS', 'yahoo',start,end)
ULTA = web.DataReader('ULTA', 'yahoo',start,end)
UNH = web.DataReader('UNH', 'yahoo',start,end)
UNM = web.DataReader('UNM', 'yahoo',start,end)
UNP = web.DataReader('UNP', 'yahoo',start,end)
UPS = web.DataReader('UPS', 'yahoo',start,end)
URBN = web.DataReader('URBN', 'yahoo',start,end)
URI = web.DataReader('URI', 'yahoo',start,end)
USB = web.DataReader('USB', 'yahoo',start,end)
UTX = web.DataReader('UTX', 'yahoo',start,end)

V = web.DataReader('V', 'yahoo',start,end)
VAR = web.DataReader('VAR', 'yahoo',start,end)
VFC = web.DataReader('VFC', 'yahoo',start,end)
VIAB = web.DataReader('VIAB', 'yahoo',start,end)
VLO = web.DataReader('VLO', 'yahoo',start,end)
VMC = web.DataReader('VMC', 'yahoo',start,end)
VNO = web.DataReader('VNO', 'yahoo',start,end)
VRSK = web.DataReader('VRSK', 'yahoo',start,end)
VRSN = web.DataReader('VRSN', 'yahoo',start,end)
VRTX = web.DataReader('VRTX', 'yahoo',start,end)
VTR = web.DataReader('VTR', 'yahoo',start,end)
VZ = web.DataReader('VZ', 'yahoo',start,end)

WAT = web.DataReader('WAT', 'yahoo',start,end)
WBA = web.DataReader('WBA', 'yahoo',start,end)
WDC = web.DataReader('WDC', 'yahoo',start,end)
WEC = web.DataReader('WEC', 'yahoo',start,end)
WFC = web.DataReader('WFC', 'yahoo',start,end)
WFM = web.DataReader('WFM', 'yahoo',start,end)
WHR = web.DataReader('WHR', 'yahoo',start,end)
WLTW = web.DataReader('WLTW', 'yahoo',start,end)
WM = web.DataReader('WM', 'yahoo',start,end)
WMB = web.DataReader('WMB', 'yahoo',start,end)
WMT = web.DataReader('WMT', 'yahoo',start,end)
WRK = web.DataReader('WRK', 'yahoo',start,end)
WU = web.DataReader('WU', 'yahoo',start,end)
WY = web.DataReader('WY', 'yahoo',start,end)
WYN = web.DataReader('WYN', 'yahoo',start,end)
WYNN = web.DataReader('WYNN', 'yahoo',start,end)

XEC = web.DataReader('XEC', 'yahoo',start,end)
XEL = web.DataReader('XEL', 'yahoo',start,end)
XL = web.DataReader('XL', 'yahoo',start,end)
XLNX = web.DataReader('XLNX', 'yahoo',start,end)
XOM = web.DataReader('XOM', 'yahoo',start,end)
XRAY = web.DataReader('XRAY', 'yahoo',start,end)
XRX = web.DataReader('XRX', 'yahoo',start,end)
XYL = web.DataReader('XYL', 'yahoo',start,end)

YHOO = web.DataReader('YHOO', 'yahoo',start,end)
YUM = web.DataReader('YUM', 'yahoo',start,end)

ZBH = web.DataReader('ZBH', 'yahoo',start,end)
ZION = web.DataReader('ZION', 'yahoo',start,end)
ZTS = web.DataReader('ZTS', 'yahoo',start,end)
print '4'
all_stocks = [A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,ADM,ADP,ADS,ADSK,AEE,AEP,AES,AET,AFL,AGN,AIG,AIV,AIZ,AJG,AKAM,ALB,ALK,ALL,ALLE,ALXN,
              AMAT,AME,AMG,AMGN,AMP,AMT,AMZN,AN,ANTM,AON,APA,APC,APD,APH,ATVI,AVB,AVGO,AVY,AWK,AXP,AYI,AZO,BA,BAC,BAX,BBBY,BBT,BBY,BCR,BDX,BEN,
              BFB,BHI,BIIB,BK,BLK,BLL,BMY,BRKB,BSX,BWA,BXP,C,CA,CAG,CAH,CAT,CB,CBG,CBS,CCI,CCL,CELG,CERN,CF,CFG,CHD,CHK,CHRW,CHTR,CI,CINF,CL,
              CLX,CMA,CMCSA,CME,CMG,CMI,CMS,CNC,CNP,COF,COG,COH,COL,COO,COP,COST,COTY,CPB,CRM,CSCO,CSRA,CSX,CTAS,CTL,CTSH,CTXS,CVS,CVX,CXO,D,DAL,
              DD,DE,DFS,DG,DGX,DHI,DHR,DIS,DISCA,DISCK,DLPH,DLR,DLTR,DNB,DOV,DOW,DPS,DRI,DTE,DUK,DVA,DVN,EA,EBAY,ECL,ED,EFX,EIX,EL,EMN,EMR,ENDP,
              EOG,EQIX,EQR,EQT,ES,ESRX,ESS,ETFC,ETN,ETR,EW,EXC,EXPD,EXPE,EXR,F,FAST,FB,FBHS,FCX,FDX,FE,FFIV,FIS,FISV,FITB,FL,FLIR,FLR,FLS,FMC,FOX,
              FOXA,FRT,FSLR,FTI,FTR,FTV,GD,GE,GGP,GILD,GIS,GLW,GM,GOOG,GOOGL,GPC,GPN,GPS,GRMN,GS,GT,GWW,HAL,HAR,HAS,HBAN,HBI,HCA,HCN,HCP,HD,HES,
              HIG,HOG,HOLX,HON,HP,HPE,HPQ,HRB,HRL,HRS,HSIC,HST,HSY,HUM,IBM,ICE,IFF,ILMN,INTC,INTU,IP,IPG,IR,IRM,ISRG,ITW,IVZ,JBHT,JCI,JEC,JNJ,JNPR,
              JPM,JWN,K,KEY,KHC,KIM,KLAC,KMB,KMI,KMX,KO,KORS,KR,KSS,KSU,L,LB,LEG,LEN,LH,LKQ,LLL,LLTC,LLY,LM,LMT,LNC,LNT,LOW,LRCX,LUK,LUV,LVLT,LYB,
              M,MA,MAC,MAR,MAS,MAT,MCD,MCHP,MCK,MCO,MDLZ,MDT,MET,MHK,MJN,MKC,MLM,MMC,MMM,MNK,MNST,MO,MON,MOS,MPC,MRK,MRO,MS,MSFT,MSI,MTB,MTD,MU,
              MUR,MYL,NAVI,NBL,NDAQ,NEE,NEM,NFLX,NFX,NI,NKE,NLSN,NOC,NOV,NRG,NSC,NTAP,NTRS,NUE,NVDA,NWL,NWS,NWSA,O,OI,OKE,OMC,ORCL,ORLY,OXY,PAYX,
              PBCT,PBI,PCAR,PCG,PCLN,PDCO,PEG,PEP,PFE,PFG,PG,PGR,PH,PHM,PKI,PLD,PM,PNC,PNR,PNW,PPG,PPL,PRGO,PRU,PSA,PSX,PVH,PWR,PX,PXD,PYPL,QCOM,
              QRVO,R,RAI,RCL,REGN,RF,RHI,RHT,RIG,RL,ROK,ROP,ROST,RRC,RSG,RTN,SBUX,SCG,SCHW,SE,SEE,SHW,SIG,SJM,SLB,SLG,SNA,SNI,SO,SPG,SPGI,SPLS,
              SRCL,SRE,STI,STJ,STT,STX,STZ,SWK,SWKS,SWN,SYF,SYK,SYMC,SYY,T,TAP,TDC,TDG,TEL,TGNA,TGT,TIF,TJX,TMK,TMO,TRIP,TROW,TRV,TSCO,TSN,TSO,TSS,
              TWX,TXN,TXT,UA,UAC,UAL,UDR,UHS,ULTA,UNH,UNM,UNP,UPS,URBN,URI,USB,UTX,V,VAR,VFC,VIAB,VLO,VMC,VNO,VRSK,VRSN,VRTX,VTR,VZ,WAT,WBA,WDC,
              WEC,WFC,WFM,WHR,WLTW,WM,WMB,WMT,WRK,WU,WY,WYN,WYNN,XEC,XEL,XL,XLNX,XOM,XRAY,XRX,XYL,YHOO,YUM,ZBH,ZION,ZTS]

for company in all_stocks:
    company['Change'] = company['Close'] - company['Open']
    company['% Change'] = (company['Change']/company['Open']) * 100
    company['Mrk Cap'] = company['Close']*company['Volume']   
    company['Return'] = np.log(company['Close']/company['Close'].shift(1))

dict = {'A':A,'AAL':AAL,'AAP':AAP,'AAPL':AAPL,'ABBV':ABBV,'ABC':ABC,'ABT':ABT,'ACN':ACN,'ADBE':ADBE,
        'ADI':ADI,'ADM':ADM,'ADP':ADP,'ADS':ADS,'ADSK':ADSK,'AEE':AEE,'AEP':AEP,'AES':AES,'AET':AET,'AFL':AFL,
        'AGN':AGN,'AIG':AIG,'AIV':AIV,'AIZ':AIZ,'AJG':AJG,'AKAM':AKAM,'ALB':ALB,'ALK':ALK,'ALL':ALL,'ALLE':ALLE,
        'ALXN':ALXN,'AMAT':AMAT,'AME':AME,'AMG':AMG,'AMGN':AMGN,'AMP':AMP,'AMT':AMT,'AMZN':AMZN,'AN':AN,
        'ANTM':ANTM,'AON':AON,'APA':APA,'APC':APC,'APD':APD,'APH':APH,'ATVI':ATVI,'AVB':AVB,'AVGO':AVGO,
        'AVY':AVY,'AWK':AWK,'AXP':AXP,'AYI':AYI,'AZO':AZO,'BA':BA,'BAC':BAC,'BAX':BAX,'BBBY':BBBY,'BBT':BBT,
        'BBY':BBY,'BCR':BCR,'BDX':BDX,'BEN':BEN,'BFB':BFB,'BHI':BHI,'BIIB':BIIB,'BK':BK,'BLK':BLK,'BLL':BLL,'BMY':BMY,'BRKB':BRKB,'BSX':BSX,'BWA':BWA,
        'BXP':BXP,'C':C,'CA':CA,'CAG':CAG,'CAH':CAH,'CAT':CAT,'CB':CB,'CBG':CBG,'CBS':CBS,'CCI':CCI,'CLL':CCL,'CELG':CELG,'CERN':CERN,'CF':CF,'CFG':CFG,
        'CHD':CHD,'CHK':CHK,'CHRW':CHRW,'CHTR':CHTR,'CI':CI,'CINF':CINF,'CL':CL,'CLX':CLX,'CMA':CMA,'CMCSA':CMCSA,'CME':CME,'CMG':CMG,'CMI':CMI,'CMS':CMS,
        'CNC':CNC,'CNP':CNP,'COF':COF,'COG':COG,'COH':COH,'COL':COL,'COO':COO,'COP':COP,'COST':COST,'COTY':COTY,'CPB':CPB,'CRM':CRM,'CSCO':CSCO,'CSRA':CSRA,
        'CSX':CSX,'CTAS':CTAS,'CTL':CTL,'CTSH':CTSH,'CTXS':CTXS,'CVS':CVS,'CVX':CVX,'CXO':CXO,'D':D,'DAL':DAL,'DD':DD,'DE':DE,'DFS':DFS,'DG':DG,'DGX':DGX,
        'DHI':DHI,'DHR':DHR,'DIS':DIS,'DISCA':DISCA,'DISCK':DISCK,'DLPH':DLPH,'DLR':DLR,'DLTR':DLTR,'DNB':DNB,'DOV':DOV,'DOW':DOW,'DPS':DPS,'DRI':DRI,
        'DTE':DTE,'	DUK':DUK,'DVA':DVA,'DVN':DVN,'EA':EA,'EBAY':EBAY,'ECL':ECL,'ED':ED,'EFX':EFX,'EIX':EIX,'EL':EL,'EMN':EMN,'EMR':EMR,'ENDP':ENDP,'EOG':EOG,
        'EQIX':EQIX,'EQR':EQR,'EQT':EQT,'ES':ES,'ESRX':ESRX,'ESS':ESS,'ETFC':ETFC,'ETN':ETN,'ETR':ETR,'EW':EW,'EXC':EXC,'EXPD':EXPD,'EXPE':EXPE,'EXR':EXR,
        'F':F,'FAST':FAST,'FB':FB,'FBHS':FBHS,'FCX':FCX,'FDX':FDX,'FE':FE,'FFIV':FFIV,'FIS':FIS,'FISV':FISV,'FITB':FITB,'FL':FL,'FLIR':FLIR,'FLR':FLR,'FLS':FLS,
        'FMC':FMC,'FOX':FOX,'FOXA':FOXA,'FRT':FRT,'FSLR':FSLR,'FTI':FTI,'FTR':FTR,'FTV':FTV,'GD':GD,'GE':GE,'GGP':GGP,'GILD':GILD,'GIS':GIS,'GLW':GLW,'GM':GM,
        'GOOG':GOOG,'GOOGL':GOOGL,'GPC':GPC,'GPN':GPN,'GPS':GPS,'GRMN':GRMN,'GS':GS,'GT':GT,'GWW':GWW,'HAL':HAL,'HAR':HAR,'HAS':HAS,'HBAN':HBAN,'HBI':HBI,
        'HCA':HCA,'HCN':HCN,'HCP':HCP,'HD':HD,'HES':HES,'HIG':HIG,'HOG':HOG,'HOLX':HOLX,'HON':HON,'HP':HP,'HPE':HPE,'HPQ':HPQ,'HRB':HRB,'HRL':HRL,'HRS':HRS,
        'HSIC':HSIC,'HST':HST,'HSY':HSY,'HUM':HUM,'IBM':IBM,'ICE':ICE,'IFF':IFF,'ILMN':ILMN,'INTC':INTC,'INTU':INTU,'IP':IP,'IPG':PG,'IR':IR,'IRM':IRM,
        'ISRG':ISRG,'ITW':ITW,'IVZ':IVZ,'JBHT':JBHT,'JCI':JCI,'JEC':JEC,'JNJ':JNJ,'JNPR':JNPR,'JPM':JPM,'JWN':JWN,'K':K,'KEY':KEY,'KHC':KHC,'KIM':KIM,
        'KLAC':KLAC,'KMB':KMB,'KMI':KMI,'KMX':KMX,'KO':KO,'KORS':KORS,'KR':KR,'KSS':KSS,'KSU':KSU,'L':L,'LB':LB,'LEG':LEG,'LEN':LEN,'LH':LH,'LKQ':LKQ,'LLL':LLL,
        'LLTC':LLTC,'LLY':LLY,'LM':LM,'LMT':LMT,'LNC':LNC,'LNT':LNT,'LOW':LOW,'LRCX':LRCX,'LUK':LUK,'LUV':LUV,'LVLT':LVLT,'LYB':LYB,'M':M,'MA':MA,'MAC':MAC,
        'MAR':MAR,'MAS':MAS,'MAT':MAT,'MCD':MCD,'MCHP':MCHP,'MCK':MCK,'MCO':MCO,'MDLZ':MDLZ,'MDT':MDT,'MET':MET,'MHK':MHK,'MJN':MJN,'MKC':MKC,'MLM':MLM,
        'MMC':MMC,'MMM':MMM,'MNK':MNK,'MNST':MNST,'MO':MO,'MON':MON,'MOS':MOS,'MPC':MPC,'MRK':MRK,'MRO':MRO,'MS':MS,'MSFT':MSFT,'MSI':MSI,'MTB':MTB,'MTD':MTD,
        'MU':MU,'MUR':MUR,'MYL':MYL,'NAVI':NAVI,'NBL':NBL,'NDAQ':NDAQ,'NEE':NEE,'NEM':NEM,'NFLX':NFLX,'NFX':NFX,'NI':NI,'NKE':NKE,'NLSN':NLSN,'NOC':NOC,
        'NOV':NOV,'NRG':NRG,'NSC':NSC,'NTAP':NTAP,'NTRS':NTRS,'NUE':NUE,'NVDA':NVDA,'NWL':NWL,'NWS':NWS,'NWSA':NWSA,'O':O,'OI':OI,'OKE':OKE,'OMC':OMC,
        'ORCL':ORCL,'ORLY':ORLY,'OXY':OXY,'PAYX':PAYX,'PBCT':PBCT,'PBI':PBI,'PCAR':PCAR,'PCG':PCG,'PCLN':PCLN,'PDCO':PDCO,'PEG':PEG,'PEP':PEP,'PFE':PFE,
        'PFG':PFG,'PG':PG,'PGR':PGR,'PH':PH,'PHM':PHM,'PKI':PKI,'PLD':PLD,'PM':PM,'PNC':PNC,'PNR':PNR,'PNW':PNW,'PPG':PPG,'PPL':PPL,'PRGO':PRGO,'PRU':PRU,
        'PSA':PSA,'PSX':PSX,'PVH':PVH,'PWR':PWR,'PX':PX,'PXD':PXD,'PYPL':PYPL,'QCOM':QCOM,'QRVO':QRVO,'R':R,'RAI':RAI,'RCL':RCL,'REGN':REGN,'RF':RF,'RHI':RHI,
        'RHT':RHT,'RIG':RIG,'RL':RL,'ROK':ROK,'ROP':ROP,'ROST':ROST,'RRC':RRC,'RSG':RSG,'RTN':RTN,'SBUX':SBUX,'SCG':SCG,'SCHW':SCHW,'SE':SE,'SEE':SEE,
        'SHW':SHW,'SIG':SIG,'SJM':SJM,'SLB':SLB,'SLG':SLG,'SNA':SNA,'SNI':SNI,'SO':SO,'SPG':SPG,'SPGI':SPGI,'SPLS':SPLS,'SRCL':SRCL,'SRE':SRE,'STI':STI,
        'STJ':STJ,'STT':STT,'STX':STX,'STZ':STZ,'SWK':SWK,'SWKS':SWKS,'SWN':SWN,'SYF':SYF,'SYK':SYK,'SYMC':SYMC,'SYY':SYY,'T':T,'TAP':TAP,'TDC':TDC,'TDG':TDG,
        'TEL':TEL,'TGNA':TGNA,'TGT':TGT,'TIF':TIF,'TJX':TJX,'TMK':TMK,'TMO':TMO,'TRIP':TRIP,'TROW':TROW,'TRV':TRV,'TSCO':TSCO,'TSN':TSN,'TSO':TSO,'TSS':TSS,
        'TWX':TWX,'TXN':TXN,'TXT':TXT,'UA':UA,'UAC':UAC,'UAL':UAL,'UDR':UDR,'UHS':UHS,'ULTA':ULTA,'UNH':UNH,'UNM':UNM,'UNP':UNP,'UPS':UPS,'URBN':URBN,
        'URI':URI,'USB':USB,'UTX':UTX,'V':V,'VAR':VAR,'VFC':VFC,'VIAB':VIAB,'VLO':VLO,'VMC':VMC,'VNO':VNO,'VRSK':VRSK,'VRSN':VRSN,'VRTX':VRTX,'VTR':VTR,'VZ':VZ,
        'WAT':WAT,'WBA':WBA,'WDC':WDC,'WEC':WEC,'WFC':WFC,'WFM':WFM,'WHR':WHR,'WLTW':WLTW,'WM':WM,'WMB':WMB,'WMT':WMT,'WRK':WRK,'WU':WU,'WY':WY,'WYN':WYN,
        'WYNN':WYNN,'XEC':XEC,'XEL':XEL,'XL':XL,'XLNX':XLNX,'XOM':XOM,'XRAY':XRAY,'XRX':XRX,'XYL':XYL,'YHOO':YHOO,'YUM':YUM,'ZBH':ZBH,'ZION':ZION,'ZTS':ZTS}
print'5'
data = pd.concat(dict.values(), axis=1, keys=dict.keys())
print sys.getsizeof(data)
data.to_csv("all_stocks.csv")

        